/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUhZcytlaDN1U2ozN25VQkcyVy9ES2twMVBPSGg1dDl2ZEJHQUsxdG1uYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUlPUzVjMjVaWlozd1hrVGErY05OZDZ4K1k0Y0hJajR2V2FObkY4YS9VYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJSXkreXFlOWhyREpVSUtjZjNZSWJFRmdKWWtCQllPOEpEamFCTVNKWlVzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhMlVqaXV0NU9DTDBlS0Vwa2FUOU1MZWU5V3VZUzhibUxld0JhcmJKdmdjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFOMVMwY0xMa0JZcmtGSCtoM1dpSjllL2sxbDRzMFJUb1FRS083eitNVkU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjdVVGVzckdpSzRYd2FibHRrYXBZS3FIYWN0SWZjOWJsZjI0QjFId3ZRRU09In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUp4Ry9DK3pwSkFXTC80R1NjWUtjSVg5d1ppenkzTWw2WWliMnUrSnRWQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK3VBUVNlUlAvSzlYVXdXbldkdDNZcWMvVHV2UnJVMWdQVnRSd1luZmtRTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjlUd015SXhKQmNZb1gveEpvOVI4SnBtRWMzNk13OHZSUmhMeFg1QXExUFdncThZOFhGd2xFM1dRbVZwYlk1QkNlaDFkK0dVVE1CTEc4ZzZ2Nk12Q2dBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTA2LCJhZHZTZWNyZXRLZXkiOiJmU3NKZkFnQStVZllkYjNPc0pHYlBVZUZ1Yy9kdkVrakJ1bWhrM1RiK1NBPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJwV0E1MS1JOVM0cUpqcVRxSjlGXzlnIiwicGhvbmVJZCI6ImNiYzAzYTE5LWFlMWUtNDc4NC1hYzliLWYzMzVjYzZlMGFlZSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJIa2N5OVRiNTFRWDhBUUVlbWtORDl2MlRLSVU9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY1FyRzdNb24yZ08zY3FYYStaWDlEcklOOEU4PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjFNTlBDSEM4IiwibWUiOnsiaWQiOiIyNjM3NzU2MTQ2Mjc6MzlAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ01QUjk4VUdFSXZ6dnJrR0dEQWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6InN2RE9VZjMxZExFbFlBMzAzV3FUSi84WE9oVzlrdDY0UStRY3IzWjdsRkE9IiwiYWNjb3VudFNpZ25hdHVyZSI6IitXN3pTTVZ4MDBHcFN3ZHc0RC9BZ3poTkVMQmQzb1owc0RiSW4wRGdaWVlzbFRDUEJzWE4vR2VZSjRJSlZMRVkxYzJ5dFJSNDZsSzdhNzhlRngrNERBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJlSEUrVWJJNW1RR29ISUdNbHpLcVNIVklKZXZzQVZLMlpHcFIvcVBsMTNqeStSR2pJcjdVclNqamFMNFI1dUkvVlJVcURGMGZjcENGSGdMMlN2ZUdqdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI2Mzc3NTYxNDYyNzozOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJiTHd6bEg5OVhTeEpXQU45TjFxa3lmL0Z6b1Z2WkxldUVQa0hLOTJlNVJRIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMxMTgwOTUzLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUdUOCJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'DON';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263775614627';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DON-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
